### ISSUE TITLE
Unable to Open PKG

### ISSUE THREAD

**Issue by EchoApeiron** [marcussacana/DirectPackageInstaller#1]
I just tried the product with a known good Google Drive link and all get is that it's unable to open the NPK: 

![image](https://user-images.githubusercontent.com/7560624/133322782-7f3ca121-d724-4d88-b1f0-6fcce9a2a6be.png)

The Google Drive link is to a PKG file and isn't compressed by any means. Not sure if there is something special that needs to be done.

**Comment by marcussacana** [comment]
You must give to him a direct link to a NPK file, the same link that your browser use to download the file, in the case of the google drive I think only the IDM can show you the download link, because the browser usually show a expired link in the download list

**Comment by marcussacana** [comment]
By the way that NPK is my typo, the correct message is "Failed to open the PKG"

**Comment by EchoApeiron** [comment]
Unfortunately, I'm not sure how to do that, but may I ask if you plan to add in support for Drive links (Drive, 1flicher, MEGA, etc)?

**Comment by marcussacana** [comment]
You can use something like this service to get the link: https://alldebrid.com/service/
The problem, he is paid... While Drive is fast to download without a paid account, the download require cookies to download, and I can't set the url cookies to the PS4 download.
