### ISSUE TITLE
Getting a "Unable to set prerequisite for package" [using DPI on LAN network]

### ISSUE THREAD

**Issue by MrLinks75** [marcussacana/DirectPackageInstaller#10]
Hi,

Currently been trying to setup DPI on my LAN network with my PS4 directly connected to my computer : 

Setup : 
PC : 192.168.1.36
PS4 : 192.168.1.38

network setup is fine, tried to log on FTP, and was able to transfer a PKG that way. 

Tried the setup /w a few PKGs, always getting the same error (cf screenshots)

![image](https://user-images.githubusercontent.com/31570259/154976197-e5db5dc5-39fd-4e3f-ad69-eb9cc85915aa.png)

Tried setting up the address in the settings.ini also, to no avail.

**Comment by marcussacana** [comment]
check if this ver show a error
[Debug.7z.zip](https://github.com/marcussacana/DirectPackageInstaller/files/8113590/Debug.7z.zip)

**Comment by marcussacana** [comment]
Then, any news?

**Comment by MrLinks75** [comment]
Hi, sorry had to figure out a few issues, tried the debug version with the same setup, wasn't able to detect the PS4. 
![image](https://user-images.githubusercontent.com/31570259/155623137-0ec188c8-6126-46aa-9826-fb4cf4028c2a.png)

Getting this error on the debug build : 
![image](https://user-images.githubusercontent.com/31570259/155623177-780bbd6e-51b9-41d7-99d9-9c1d611e3565.png)

It seems the regular version after forcing the IP address seems to be working.

**Comment by marcussacana** [comment]
If possible check if this version still buggy:
[DirectPackageInstaller.7z.zip](https://github.com/marcussacana/DirectPackageInstaller/files/8138440/DirectPackageInstaller.7z.zip)

**Comment by epiclulz666** [comment]
this is a common error that i have also seen myself with the other package sender app "remotepackagesender" in that instance its normally a connection issue or time out issue between the app but also has been noted a couple of places as being a bug related to the latest goldenhen payload

**Comment by marcussacana** [comment]
> this is a common error that i have also seen myself with the other package sender app "remotepackagesender" in that instance its normally a connection issue or time out issue between the app but also has been noted a couple of places as being a bug related to the latest goldenhen payload

First time I hear about this be a goldhen related bug, I will try keep that in mind, since that make sense a bit, the JB must apply the flatz patches to the RemotePackageInstaller works after all.

**Comment by epiclulz666** [comment]
my bad i was getting it mixed up with the time out errror, the error from this thread is explained here 

https://github.com/iref-use/ps4-remote-pkg-sender/blob/master/Troubleshoot.md#unable-to-set-up-prerequisites-for-package

**Comment by marcussacana** [comment]
Ohh, this one
