### ISSUE TITLE
Android ?

### ISSUE THREAD

**Issue by Mad-sl67** [marcussacana/DirectPackageInstaller#15]
Wish if there's a way to use this on android devices

**Comment by marcussacana** [comment]
This guy had sucess running in android:
https://github.com/marcussacana/DirectPackageInstaller/issues/3#issuecomment-1133940970

So, if the question is if there's a way, then yes, but not officially, at least for now.

**Comment by Mad-sl67** [comment]
I see .. but i don't know how he did it 
Is it some kind of emulator? 
A tutorial would be better

**Comment by marcussacana** [comment]
Well, I don't know too, he didn't said, but I supose should be something with a terminal emulator runing linux.
Something like this maybe: https://github.com/MFDGaming/ubuntu-in-termux

**Comment by Mad-sl67** [comment]
I will search in youtube about this emulator, maybe this will work
and if u can add this directpackageInstaller in a website it will be better, Anyway thank u

**Comment by Mad-sl67** [comment]
> Well, I don't know too, he didn't said, but I supose should be something with a terminal emulator runing linux. Something like this maybe: https://github.com/MFDGaming/ubuntu-in-termux

I installed debian 10 on my phone
But i dont know how to run directpackageinstaller and how to install net 6

**Comment by Mad-sl67** [comment]
![Screenshot_2022-05-30-00-06-43-353_com iiordanov freebVNC](https://user-images.githubusercontent.com/99123936/170895011-dd0def0e-fc08-4309-bcea-6e4a715bf639.jpg)

It's the first time i use linux
If it can work on my phone i could really use your help if u have time

**Comment by marcussacana** [comment]
You can install https://docs.microsoft.com/en-us/dotnet/core/install/linux
