### ISSUE TITLE
NAS synology problem

### ISSUE THREAD

**Issue by vservis1** [marcussacana/DirectPackageInstaller#17]
eagle from psxplace
known problem when i want to load fpkg from synology
i can OPEN pkg, but when want to load then LOAD then i get message analyizing ... and get failed to open pkg
im using simply samba sharing.
![screenshot](https://user-images.githubusercontent.com/106911172/172047638-01d52ad7-528d-4643-8090-3ee133fc1ddb.jpg)

regards

**Comment by marcussacana** [comment]
I think if you map a network drive in your Windows should works.
Anyway, I tried fix this error, but no idea if it's fixed since I don't have an SMB server with an pkg, test this build:
[Windows-X64.zip](https://github.com/marcussacana/DirectPackageInstaller/files/8840210/Windows-X64.zip)

**Comment by vservis1** [comment]
now working from synology NAS
implant this in next version of great progy!
some progress bar will be nice to see in next release!
thanx for your work

**Comment by marcussacana** [comment]
Compatiblity added in 6.1.2
