### ISSUE TITLE
Add filecrypt support

### ISSUE THREAD

**Issue by tehrzky** [marcussacana/DirectPackageInstaller#19]
android cant extract Jdownloader "Click'n Load" on this site. 

love this app , this APP has a ESHOP potential.  all you need is a list of any kind of pkg

**Comment by marcussacana** [comment]
The Click'n Load works on android or PC even without Jdownloader, just go to `Options -> CNL Support`

**Comment by tehrzky** [comment]
ah ok tnx. one of the best app for ps4.
