### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by shakeyourbunny** [marcussacana/DirectPackageInstaller#2]
Could you provide a Linux version?

**Comment by marcussacana** [comment]
It is possible, but not immediately, in a while I will format the computer and I can leave a partition with linux to develop, in the last case WSL

**Comment by marcussacana** [comment]
The Proxy Download mode works as well?

**Comment by shpyntov** [comment]
I can't test this feature - I don't have any proxys and server with pkg file :(

**Comment by marcussacana** [comment]
You don't need one, the program take a care of anything to you in that mode.

**Comment by shpyntov** [comment]
It works!

**Comment by shpyntov** [comment]
Finally:

1 - If he can found the correct PS4 IP automatically - PASS, but finding too slow
2 - If he can send a package to direct download in the PS4 - PASS
3 - If the Proxy Download feature is working (with big files if possible) - PASS
4 - If he has able to open a .rar pkg (don't need to try install, but test it will be welcome) - FAIL

**Comment by marcussacana** [comment]
Okay, thank you.
Just a question about the Proxy Download, that feature is more usefull if you're downloading a pkg from a remote url, anyway, in your tests you noticied if the Proxy Feature made the download faster or slower?

**Comment by shpyntov** [comment]
It made downloading slower
