### ISSUE TITLE
Application closing

### ISSUE THREAD

**Issue by 00edit** [marcussacana/DirectPackageInstaller#21]
The software closes on its own for some reason and my whole download fails and I have to restart all over again. Hope you can fix it, please and thank you

**Comment by marcussacana** [comment]
A Crash.log file should be found in the application folder, send me that file.
In android the file should be located at /Android/Data/com.marcussacana.DirectPackageInstaller/files

**Comment by 00edit** [comment]
There isn't crash.log file, when the app closes and it doesn't look like as if it crashes or lags, freezes, it just disappears. Am retrying now without proxy downloads and gonna let you know what happens. Am sorry if it's just me doing something wrong and app is fine, but I will let you know.

**Comment by marcussacana** [comment]
What platform you're runinng?

**Comment by 00edit** [comment]
Windows 10 - PS4 9.00 UPDATE: so I tried it again and left it over night it worked without the app closing and proxy downloads off while also having remote package installer open too

**Comment by marcussacana** [comment]
Try this
1 - Open the CMD in the DirectPackageInstaller directory
2 - run `dotnet DirectPackageInstaller.Desktop.dll`
3 - make the DirectPackageInstaller crashes.
Check if the CMD will display any error info.
