### ISSUE TITLE
great tool but having some issue

### ISSUE THREAD

**Issue by ifelixculpa** [marcussacana/DirectPackageInstaller#23]
this is a fast and wonderful tool but when I try to send multiple files I get some dpi error attaching 2 images with 1 getting in successfully but other showing an error

![Screenshot_1](https://user-images.githubusercontent.com/13099434/185810063-9bf5e047-ea65-487f-ab43-a5a8b38aebc4.png)
![Screenshot_2](https://user-images.githubusercontent.com/13099434/185810043-5b448718-48d8-49bc-aa7c-94f124fa43dd.png)

**Comment by marcussacana** [comment]
Look like this error is `SCE_BGFT_ERROR_BROKEN_PACKET`
Did you downloaded from compressed file, this bug happens all times that you try install certain file or is rare?

**Comment by ifelixculpa** [comment]
> Look like this error is `SCE_BGFT_ERROR_NOT_SUPPORTED` Did you downloaded from compressed file?, this bug happens all times that you try install certain file or is random?

i lined up 2 pkg files again and it this time showed a notification of something pushed to ps4 but nothing happened there

**Comment by marcussacana** [comment]
I noticied the bug when you flood packages, usually you will need reboot the PS4 to works again...
I think the problem here is the payload restarting for each download and re-initializing the BGFT service,
Maybe a soluction for that should create a payload that keep alive in background, but is a bit different of the how the current method works. 
The wrose thing creating things for PS4 without a proper devkit, is how I can't debug my tool at all, it's hard to me find a bug like this without debug.
Currently, we have a old branch with a custom payload, you will need build by yourself but this one as some fixes that theorically should be more stable, but I never had time for a proper testing, so I never released in the main branch, give a look if you want, just build the payload with `make` and replace the binary file in `DirectPackageInstaller/DirectPackageInstaller/payload` If I had reports of that version doing better I can release it.

**Comment by ifelixculpa** [comment]
> I noticied the bug when you flood packages, usually you will need reboot the PS4 to works again... I think the problem here is the payload restarting for each download and re-initializing the BGFT service, Maybe a soluction for that should create a payload that keep alive in background, but is a bit different of the how the current method works. The wrose thing creating things for PS4 without a proper devkit, is how I can't debug my tool at all, it's hard to me find a bug like this without debug. Currently, we have a old branch with a custom payload, you will need build by yourself but this one as some fixes that theorically should be more stable, but I never had time for a proper testing, so I never released in the main branch, give a look if you want, just build the payload with `make` and replace the binary file in `DirectPackageInstaller/DirectPackageInstaller/payload` If I had reports of that version doing better I can release it.

i can try but my knowledge on building things is limited , how do i run make file ?

**Comment by ifelixculpa** [comment]
> I noticied the bug when you flood packages, usually you will need reboot the PS4 to works again... I think the problem here is the payload restarting for each download and re-initializing the BGFT service, Maybe a soluction for that should create a payload that keep alive in background, but is a bit different of the how the current method works. The wrose thing creating things for PS4 without a proper devkit, is how I can't debug my tool at all, it's hard to me find a bug like this without debug. Currently, we have a old branch with a custom payload, you will need build by yourself but this one as some fixes that theorically should be more stable, but I never had time for a proper testing, so I never released in the main branch, give a look if you want, just build the payload with `make` and replace the binary file in `DirectPackageInstaller/DirectPackageInstaller/payload` If I had reports of that version doing better I can release it.

getting this error

![image](https://user-images.githubusercontent.com/13099434/185813421-a28da2b7-ed6c-4de6-857d-2d2712f399c1.png)

**Comment by marcussacana** [comment]
You can use the github actions to build, but still need to build the payload manually and update in the git the payload binary, because the build script don't rebuild the payload as well.

**Comment by ifelixculpa** [comment]
> You can use the github actions to build, but still need to build the payload manually and update in the git the payload binary, because the build script don't rebuild the payload as well.

sorry mate i aint big of techie guy :)

**Comment by marcussacana** [comment]
Yup, you started, but as said, the DirectPackageInstaller has 2 components, the Payload and the Sender, you are building only the sender.
the payload side (what has been fixed in [Payload-Fix-Test](https://github.com/marcussacana/DirectPackageInstaller/tree/Payload-Fix-Test)) you must manually build with `make`. it was made to be built in linux, I never tried build from windows before.

**Comment by ifelixculpa** [comment]
> Yup, you started, but as said, the DirectPackageInstaller has 2 components, the Payload and the Sender, you are building only the sender. the payload side (what has been fixed in [Payload-Fix-Test](https://github.com/marcussacana/DirectPackageInstaller/tree/Payload-Fix-Test)) you must manually build with `make`. it was made to be built in linux, I never tried build from windows before.

are there any steps to build , i can arrange linux pc tomorrow from someone and test

**Comment by marcussacana** [comment]
literally, just run `make`
![image](https://user-images.githubusercontent.com/10576957/185814941-1effd101-14f7-4678-9e71-d1e12b2aba9c.png)
Anyway, I did here, replace with the file in the DirectpackageInstaller/DirectPackageInstaller directory and push to your fork, then trigger the github action again.
[payload.zip](https://github.com/marcussacana/DirectPackageInstaller/files/9390114/payload.zip)

**Comment by ifelixculpa** [comment]
> literally, just run `make` ![image](https://user-images.githubusercontent.com/10576957/185814941-1effd101-14f7-4678-9e71-d1e12b2aba9c.png) Anyway, I did here, replace with the file in the DirectpackageInstaller/DirectPackageInstaller directory and push to your fork, then trigger the github action again. [payload.zip](https://github.com/marcussacana/DirectPackageInstaller/files/9390114/payload.zip)

thanks , but atleast i can now keep up with future updates and changes to keep u posted :)

thanks il test and report

**Comment by ifelixculpa** [comment]
> literally, just run `make` ![image](https://user-images.githubusercontent.com/10576957/185814941-1effd101-14f7-4678-9e71-d1e12b2aba9c.png) Anyway, I did here, replace with the file in the DirectpackageInstaller/DirectPackageInstaller directory and push to your fork, then trigger the github action again. [payload.zip](https://github.com/marcussacana/DirectPackageInstaller/files/9390114/payload.zip)

![image](https://user-images.githubusercontent.com/13099434/185815108-12e9540a-91ee-4831-b491-124b22d8bd14.png)


does it takes this much time ? or is my pc acting strange

**Comment by marcussacana** [comment]
it does, from 40~50m

**Comment by ifelixculpa** [comment]
> it does, from 40~50m

thanks il report back  , just to sure once it completes will there be any downloads ? within which i need to replace the file and push back ?

**Comment by ifelixculpa** [comment]
> it does, from 40~50m

![image](https://user-images.githubusercontent.com/13099434/185815325-d7d4616f-2ac9-44d3-b417-5af3182acbf7.png)

**Comment by marcussacana** [comment]
just scroll down
![image](https://user-images.githubusercontent.com/10576957/185860152-354b3e8e-e239-4364-a630-ba3aed3d2bd9.png)

**Comment by ifelixculpa** [comment]
> just scroll down
> ![image](https://user-images.githubusercontent.com/10576957/185860152-354b3e8e-e239-4364-a630-ba3aed3d2bd9.png)
> 

Yes downloaded this to pc last night sir what after this

**Comment by marcussacana** [comment]
As a said, you should replace the payload binary in the DirectPackageInstaller with the one that I gave to you, but seems that you didn't that.
https://github.com/ifelixculpa/DirectPackageInstaller/blob/main/DirectPackageInstaller/DirectPackageInstaller/payload
This one, if you replace that with the one that I gave to you, the github actions will be trigerred automatically and you create a new version of the DirectPackageInstaller using this custom payload.

**Comment by ifelixculpa** [comment]
> As a said, you should replace the payload binary in the DirectPackageInstaller with the one that I gave to you, but seems that you didn't that. https://github.com/ifelixculpa/DirectPackageInstaller/blob/main/DirectPackageInstaller/DirectPackageInstaller/payload This one, if you replace that with the one that I gave to you, the github actions will be trigerred automatically and you create a new version of the DirectPackageInstaller using this custom payload.

i am trying to learn all this is new to me sir , still trying my best il let u know once i figure this out ...on how to replace where is it located

**Comment by marcussacana** [comment]
You sure did, but you forget to remove the .bin extension, the old file still being used.

**Comment by ifelixculpa** [comment]
> You sure did, but you forget to remove the .bin extension, the old file still being used.

lol let me do again

**Comment by marcussacana** [comment]
yup, now is right

**Comment by ifelixculpa** [comment]
> yup, now is right

completed , have downloaded the zip and extracted the windows x64 ... how do i verify i have correct version

**Comment by marcussacana** [comment]
No way to verify, but probabbly you have it.
maybe you can verify if you open a 9090 TCP server and send as if is a ps4 to check the payload data, but that's a bit crazy just to check it.

**Comment by ifelixculpa** [comment]
> No way to verify, but probabbly you have it. maybe you can verify if you open a 9090 TCP server and send as if is a ps4 to check the payload data, but that's a bit crazy just to check it.

i think it ends up same il try a small video of whats happening

**Comment by ifelixculpa** [comment]
> No way to verify, but probabbly you have it. maybe you can verify if you open a 9090 TCP server and send as if is a ps4 to check the payload data, but that's a bit crazy just to check it.

here it is , if you can figure out or what i am doing wrong

**Comment by marcussacana** [comment]
you restarted your PS4?

**Comment by ifelixculpa** [comment]
> you restarted your PS4?

nope , i would have lost jailbreak then

**Comment by ifelixculpa** [comment]
if you have any other way to communicate much faster like telegram let me know , have another thing to share :)

**Comment by marcussacana** [comment]
you should restart, sometime the goldhen payload server hangs and became unresponsible, not sure if is your case right here.

**Comment by ifelixculpa** [comment]
> you should restart, sometime the goldhen payload server hangs and became unresponsible, not sure if is your case right here.

I restarted and rejailbreak but app doesnt seem to work with large files...works well with smaller packages only

**Comment by marcussacana** [comment]
that's strange...
Well, to make the things better I should make a one-time payload to keep running in background instead the current one that must be sent for each installation.
But it's a pain to me create payloads since I can't debug at all, the debugger in my PS4 just never worked.
I will keep this open for now, in the future if I feel like I can try reimplement the payload

**Comment by ifelixculpa** [comment]
> that's strange... Well, to make the things better I should make a one-time payload to keep running in background instead the current one that must be sent for each installation. But it's a pain to me create payloads since I can't debug at all, the debugger in my PS4 just never worked. I will keep this open for now, in the future if I feel like I can try reimplement the payload

i am always here to test :)

**Comment by marcussacana** [comment]
The new version 6.2.0 has now a improved GoldHEN method, then I'm closing this issue for now.
You may free to test, if you found new problems create a new issue or open this one :)
