### ISSUE TITLE
Transfers resets

### ISSUE THREAD

**Issue by RAAGO82494** [marcussacana/DirectPackageInstaller#24]
Hello! First of all sorry for my horrible english, i just wanted to create an issue, because i'm having trouble when i want to transfer updates to my PS4, it resets everytime it gets to 50-60 mb and then starts again in an infinite loop, maybe it's just me or i'm doing something wrong; as i said it only happens with the updates, that's it, greetings!

**Comment by marcussacana** [comment]
that's normal, the connection may be a bit unstable with you but the download look like is reseting but isn't, you may notice the total download size decreasing when the download restarts

**Comment by RAAGO82494** [comment]
Ohhh i didn't knew that, i'm sorry for that, and thanks for the rapid response
