### ISSUE TITLE
Cookies 

### ISSUE THREAD

**Issue by Firasbaklouti1** [marcussacana/DirectPackageInstaller#25]
I used drive Google link and then i recived "enter cookies"
Then pkg faild

**Comment by marcussacana** [comment]
The GDrive requires an account to download some files, you can use this extension to create a cookies.txt
https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid
Execute the extension with the gdrive page open, then Copy and paste the content of the downloaded .txt into the DirectPackageInstaller "Enter Cookies" Window

**Comment by Firasbaklouti1** [comment]
I did like you Say but i got another message
"Système exception: Exception was thrown............"
What must i do?


Le dim. 28 août 2022 à 16:30, Marcus André ***@***.***> a
écrit :

**Comment by Firasbaklouti1** [comment]
I did like you Say but i got another message 
"Système exception: Exception was thrown............"
What must i do?

**Comment by marcussacana** [comment]
Missing information, I need the entire log
