### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by acazmaj144** [marcussacana/DirectPackageInstaller#27]
hi, first few times i installed game perfectly fine but next day i just get this error messages whenever i try to install any new game
i have 400gb free space on my pc and arround 250gb on my ps4 pro, from every link i try and nothing, works just when i download some pkg file on my pc then load it with app.......here is the error message
Failed to load URL info
this log are created in app directory
DPI ERROR
DirectPackageInstaller.Others.AbortException: Failed to load URL info
   at DirectPackageInstaller.Views.MainView.LoadUrl(String SourcePackage) in /home/marcus/Documentos/GitHub/DirectPackageInstaller/DirectPackageInstaller/DirectPackageInstaller/Views/MainView.axaml.cs:line 518
   at DirectPackageInstaller.Views.MainView.BtnLoadOnClick(Object sender, RoutedEventArgs e) in /home/marcus/Documentos/GitHub/DirectPackageInstaller/DirectPackageInstaller/DirectPackageInstaller/Views/MainView.axaml.cs:line 385

please help

**Comment by marcussacana** [comment]
send the url that you're tryling load to my email: ddtank.marcus@gmail.com

**Comment by acazmaj144** [comment]
i forgot to add.... same thing happens when i try to load on my phone or my other pc
i even try doing it over my cellular network or connecting to local caffe wi-fi

**Comment by acazmaj144** [comment]
i was trying to load multiple urls from multiple games and multiple sites
all same

**Comment by marcussacana** [comment]
Maybe you have a firewall or anything blocking the DPI connection?

**Comment by acazmaj144** [comment]
im not sure, i tried on multiple mobile phones and my other pc, even on my celllular network and coffe shop network

**Comment by marcussacana** [comment]
Fine, give me some minutes, I will test, maybe zippyshare is broken again

**Comment by acazmaj144** [comment]
ok thank you

**Comment by marcussacana** [comment]
Fixed!, I will upload the fix in some minutes.
![image](https://user-images.githubusercontent.com/10576957/201222899-80998db6-9722-4fc6-a210-c36ab06616d7.png)

**Comment by marcussacana** [comment]
test it
