### ISSUE TITLE
Payload sended but no installation started

### ISSUE THREAD

**Issue by Vikksxz** [marcussacana/DirectPackageInstaller#29]
i've selected the .pkg file from my computer, the app recognized it as the game but when i hit install, in the ps4 i do recieve the pop up notification that the goldhen recieved a payload from my pc IP but doesn't start the installation process. Also in the app i don't recieve the message that the payload have been sended.
Sorry for my bad english if its needed some kind of details just tell me and i will answer as fast as i can.
Very nice app thatnks for all.

**Comment by marcussacana** [comment]
1 - Restart the PS4
2 - Test a different pkg

**Comment by Vikksxz** [comment]
OK, i Will try. Thanks for the attentionDe: Marcus AndréEnviado: lunes, 14 de noviembre de 2022 23:05Para: marcussacana/DirectPackageInstallerCC: Vikksxz; AuthorAsunto: Re: [marcussacana/DirectPackageInstaller] Payload sended but no installation started (Issue #29) 1 - Restart the PS42 - Test a different pkg—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
