### ISSUE TITLE
Using curl in linux 

### ISSUE THREAD

**Issue by seisdr** [marcussacana/DirectPackageInstaller#3]
In https://github.com/flatz/ps4_remote_pkg_installer/ readme shows that i can use a local server but i dont want to i have a direct pkg link to a full gane from near by server  which curl syntaxt should i use ?

**Comment by marcussacana** [comment]
Test this linux build: https://github.com/marcussacana/DirectPackageInstaller/issues/2#issuecomment-954135875
you must install the mono-runtime and libgdiplus packages to work.

**Comment by seisdr** [comment]
I cant i want to use a my phone with terminal emulator

**Comment by seisdr** [comment]
With this link "https://shdw3.shabakaty.com/share2019/873847909?AWSAccessKeyId=F9TVSC15H6I4WV1S457P&Expires=1639692505&response-content-disposition=attachment%3Bfilename%3D%22Grand-Theft-Auto-V-Premium-Edition-CUSA00419-A0100-V0100.pkg%22&response-content-encoding=System.Text.UTF8Encoding%2BUTF8EncodingSealed&response-content-type=application%2Foctet-stream&Signature=mwyltse5TiwBYoGWHFqmCiiiUf8%3D"
You cant access it but its a direct link to gta 5 full game on one pkg file

**Comment by marcussacana** [comment]
You can use the direct link as long him don't need any cookie or special header to allow the connection, some few links don't works as well because the PS4 downloader add some few parameters in the url while downloading, and with that some download servers can refuse the download.

**Comment by seisdr** [comment]
Well if you could make ur app cli only and for 32bit i can run it on my phone

**Comment by seisdr** [comment]
Print the pkg info on cli thats fun

**Comment by marcussacana** [comment]
huh, did you managed to run the mono-runtime in your phone?

**Comment by seisdr** [comment]
I can use huawei emulator to emulate x64 and x86 on my phone installing mono-runtime is not a big deal neither running this program but because its gui my phone cant handle it

**Comment by marcussacana** [comment]
If you run ubuntu touch for example, you should be able to build the program to ARM and run natively.
maybe if you manage to run the mono-runtime in termux you can really do something if I port the tool to CLI

**Comment by seisdr** [comment]
Yeah i can 
`root@localhost:~# mono --version                                Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1ubuntu1)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread                                         SIGSEGV:       altstack
        Notifications: epoll                                            Architecture:  x86
        Disabled:      none                                             Misc:          softdebug
        LLVM:          supported, not enabled.                          GC:            sgen`

**Comment by marcussacana** [comment]
the new version has CLI, but you must be able to install the dotnet 6, not sure if will works well in your phone

**Comment by seisdr** [comment]
![Screenshot_2022-05-22-20-35-37-67_92b64b2a7aa6eb3771ed6e18d0029815](https://user-images.githubusercontent.com/45742462/169708185-5277d4fd-f5b7-49f4-b566-3baacb06168c.jpg)
It did work, arm64, i can't fully test it right now

**Comment by marcussacana** [comment]
use `-help` to see the command line arguments

**Comment by seisdr** [comment]
```
root@localhost:~/test# ./DirectPackageInstaller.Desktop -Server 192.168.0.198  -PS4 192.168.0.195:12800    "https://shdw3.shabakaty.com/sharec/415158902?AWSAccessKeyId=F9TVSC15H6I4WV1S457P&Expires=1653935723&response-content-disposition=attachment%3Bfilename%3D%22DESERT%20STOROM%20III.pkg%22&response-content-encoding=System.Text.UTF8Encoding%2BUTF8EncodingSealed&response-content-type=application%2Foctet-stream&Signature=eVujrFe8zvgLWZmwCrKkvCwuXZs%3D"
DirectPacakgeInstaller v6.0.3 - CLI
LAN: 192.168.0.198
PS4: 192.168.0.195:12800
Source: https://shdw3.shabakaty.com/sharec/415158902?AWSAccessKeyId=F9TVSC15H6I4WV1S457P&Expires=1653935723&response-content-disposition=attachment%3Bfilename%3D%22DESERT%20STOROM%20III.pkg%22&response-content-encoding=System.Text.UTF8Encoding%2BUTF8EncodingSealed&response-content-type=application%2Foctet-stream&Signature=eVujrFe8zvgLWZmwCrKkvCwuXZs%3D
Pusing: DESERT STORM 3
Title ID: CUSA00014
Content ID: UP9000-CUSA00014_00-SCUS974900000001
Type: Game Digital Application (gd)
Failed to Send the PKG
root@localhost:~/test#
```

**Comment by Mad-sl67** [comment]
> ```
> root@localhost:~/test# ./DirectPackageInstaller.Desktop -Server 192.168.0.198  -PS4 192.168.0.195:12800    "https://shdw3.shabakaty.com/sharec/415158902?AWSAccessKeyId=F9TVSC15H6I4WV1S457P&Expires=1653935723&response-content-disposition=attachment%3Bfilename%3D%22DESERT%20STOROM%20III.pkg%22&response-content-encoding=System.Text.UTF8Encoding%2BUTF8EncodingSealed&response-content-type=application%2Foctet-stream&Signature=eVujrFe8zvgLWZmwCrKkvCwuXZs%3D"
> DirectPacakgeInstaller v6.0.3 - CLI
> LAN: 192.168.0.198
> PS4: 192.168.0.195:12800
> Source: https://shdw3.shabakaty.com/sharec/415158902?AWSAccessKeyId=F9TVSC15H6I4WV1S457P&Expires=1653935723&response-content-disposition=attachment%3Bfilename%3D%22DESERT%20STOROM%20III.pkg%22&response-content-encoding=System.Text.UTF8Encoding%2BUTF8EncodingSealed&response-content-type=application%2Foctet-stream&Signature=eVujrFe8zvgLWZmwCrKkvCwuXZs%3D
> Pusing: DESERT STORM 3
> Title ID: CUSA00014
> Content ID: UP9000-CUSA00014_00-SCUS974900000001
> Type: Game Digital Application (gd)
> Failed to Send the PKG
> root@localhost:~/test#
> ```

I have some questions for u bro, how can i contact u?

**Comment by seisdr** [comment]
> > ```
> > root@localhost:~/test# ./DirectPackageInstaller.Desktop -Server 192.168.0.198  -PS4 192.168.0.195:12800    "https://shdw3.shabakaty.com/sharec/415158902?AWSAccessKeyId=F9TVSC15H6I4WV1S457P&Expires=1653935723&response-content-disposition=attachment%3Bfilename%3D%22DESERT%20STOROM%20III.pkg%22&response-content-encoding=System.Text.UTF8Encoding%2BUTF8EncodingSealed&response-content-type=application%2Foctet-stream&Signature=eVujrFe8zvgLWZmwCrKkvCwuXZs%3D"
> > DirectPacakgeInstaller v6.0.3 - CLI
> > LAN: 192.168.0.198
> > PS4: 192.168.0.195:12800
> > Source: https://shdw3.shabakaty.com/sharec/415158902?AWSAccessKeyId=F9TVSC15H6I4WV1S457P&Expires=1653935723&response-content-disposition=attachment%3Bfilename%3D%22DESERT%20STOROM%20III.pkg%22&response-content-encoding=System.Text.UTF8Encoding%2BUTF8EncodingSealed&response-content-type=application%2Foctet-stream&Signature=eVujrFe8zvgLWZmwCrKkvCwuXZs%3D
> > Pusing: DESERT STORM 3
> > Title ID: CUSA00014
> > Content ID: UP9000-CUSA00014_00-SCUS974900000001
> > Type: Game Digital Application (gd)
> > Failed to Send the PKG
> > root@localhost:~/test#
> > ```
> 
> I have some questions for u bro, how can i contact u?

Discord? @Spiral#9643

**Comment by Mad-sl67** [comment]
> > > ```
> > > root@localhost:~/test# ./DirectPackageInstaller.Desktop -Server 192.168.0.198  -PS4 192.168.0.195:12800    "https://shdw3.shabakaty.com/sharec/415158902?AWSAccessKeyId=F9TVSC15H6I4WV1S457P&Expires=1653935723&response-content-disposition=attachment%3Bfilename%3D%22DESERT%20STOROM%20III.pkg%22&response-content-encoding=System.Text.UTF8Encoding%2BUTF8EncodingSealed&response-content-type=application%2Foctet-stream&Signature=eVujrFe8zvgLWZmwCrKkvCwuXZs%3D"
> > > DirectPacakgeInstaller v6.0.3 - CLI
> > > LAN: 192.168.0.198
> > > PS4: 192.168.0.195:12800
> > > Source: https://shdw3.shabakaty.com/sharec/415158902?AWSAccessKeyId=F9TVSC15H6I4WV1S457P&Expires=1653935723&response-content-disposition=attachment%3Bfilename%3D%22DESERT%20STOROM%20III.pkg%22&response-content-encoding=System.Text.UTF8Encoding%2BUTF8EncodingSealed&response-content-type=application%2Foctet-stream&Signature=eVujrFe8zvgLWZmwCrKkvCwuXZs%3D
> > > Pusing: DESERT STORM 3
> > > Title ID: CUSA00014
> > > Content ID: UP9000-CUSA00014_00-SCUS974900000001
> > > Type: Game Digital Application (gd)
> > > Failed to Send the PKG
> > > root@localhost:~/test#
> > > ```
> > 
> > 
> > I have some questions for u bro, how can i contact u?
> 
> Discord? @spiral#9643

I tried but u are disabling friend requests
Can u try mine ? mil.sd#6181

**Comment by marcussacana** [comment]
> ```
> root@localhost:~/test# ./DirectPackageInstaller.Desktop -Server 192.168.0.198  -PS4 192.168.0.195:12800    "https://shdw3.shabakaty.com/sharec/415158902?AWSAccessKeyId=F9TVSC15H6I4WV1S457P&Expires=1653935723&response-content-disposition=attachment%3Bfilename%3D%22DESERT%20STOROM%20III.pkg%22&response-content-encoding=System.Text.UTF8Encoding%2BUTF8EncodingSealed&response-content-type=application%2Foctet-stream&Signature=eVujrFe8zvgLWZmwCrKkvCwuXZs%3D"
> DirectPacakgeInstaller v6.0.3 - CLI
> LAN: 192.168.0.198
> PS4: 192.168.0.195:12800
> Source: https://shdw3.shabakaty.com/sharec/415158902?AWSAccessKeyId=F9TVSC15H6I4WV1S457P&Expires=1653935723&response-content-disposition=attachment%3Bfilename%3D%22DESERT%20STOROM%20III.pkg%22&response-content-encoding=System.Text.UTF8Encoding%2BUTF8EncodingSealed&response-content-type=application%2Foctet-stream&Signature=eVujrFe8zvgLWZmwCrKkvCwuXZs%3D
> Pusing: DESERT STORM 3
> Title ID: CUSA00014
> Content ID: UP9000-CUSA00014_00-SCUS974900000001
> Type: Game Digital Application (gd)
> Failed to Send the PKG
> root@localhost:~/test#
> ```

You can't put a PS4 ip:port like that.
-Port is what you can use to set the payload port
And you don't need to put the -Server -PS4 parameters, those values are automatically detected,
Try without first, if fail to find your IP, then you put it again.

**Comment by seisdr** [comment]
I did and it didn't work , but with gui it does work
![Screenshot_2022-05-30-19-03-59-63_8659c1e795b4b4239e38d87c88c077b3](https://user-images.githubusercontent.com/45742462/171030082-3c8cab58-dd0b-474f-985e-2829dac7b087.jpg)

**Comment by marcussacana** [comment]
The CLI version only works with goldhen method, if you tried send to remote package installer don't will works.

**Comment by seisdr** [comment]
What golden hen method

**Comment by marcussacana** [comment]
Close the Remote Package Installer and enable the GoldHEN Payload server
