### ISSUE TITLE
Does it work with splited archive

### ISSUE THREAD

**Issue by ulist** [marcussacana/DirectPackageInstaller#32]
Like this one
![Screenshot_٢٠٢٣-٠٢-٠٣-١٨-١١-٠٩-٥٢_fc83a5aa594c7bb48e851b81b4b1f8f8](https://user-images.githubusercontent.com/39057208/216638380-83abd1eb-09d8-4521-92ed-63441b13e25f.jpg)

**Comment by marcussacana** [comment]
The tool works with splited rar if the source is a url.
currently, the DPI can't read rar/7z files downloaded locally.
