### ISSUE TITLE
getting error while sending pkg

### ISSUE THREAD

**Issue by ifelixculpa** [marcussacana/DirectPackageInstaller#34]
though after first coiuple of games it went super amazing but after that it started showing this error

![image](https://user-images.githubusercontent.com/13099434/217901611-655c3bbe-29f5-4883-a460-2a1f1a43e2c5.png)

**Comment by ifelixculpa** [comment]
> Your PS4 HD is full basically.
> delete some games, but it's strange how can't install such small homebrew...
> if you delete something bigger and still give the same error, then may be a problem.
> the flatz description to this error is:
> `Not enough storage space to allocate a set of contiguous free area for installation of the specified pkg.`

I have installed 2tb hdd on my PS4 and I still have around 1.1 tb empty

**Comment by marcussacana** [comment]
You tried use the goldhen method instead?
should give an different error maybe.

**Comment by ifelixculpa** [comment]
> You tried use the goldhen method instead?
> should give an different error maybe.

Il try tomorrow as not with PS4 anymore... Thankyou

**Comment by ifelixculpa** [comment]
sorted , dont know what the error was...but this has to be the fastest wireless transfer app ... awesome
