### ISSUE TITLE
DPI crash when selecting a PKG

### ISSUE THREAD

**Issue by JNKD0G** [marcussacana/DirectPackageInstaller#35]
[DPI-CARSH.log](https://github.com/marcussacana/DirectPackageInstaller/files/10716907/DPI-CARSH.log)
The app crashes immediately after I choose the pkg, I don't know what I'm doing wrong. I'm on windows 7 64bit and i've installed the .net apps.

**Comment by marcussacana** [comment]
A DPI-Crash.log file should exist in the DPi directory, upload that file

**Comment by JNKD0G** [comment]
There it is my friend

**Comment by marcussacana** [comment]
Seem to be a avalonia problem, is there anything special in the file location that you are trying open?
Like a remote disk directory, very long path, special characters in the path... anything came in your mind?

We should look into this issue, but you may try just drag&drop the file for now.

**Comment by JNKD0G** [comment]
Yeah I think it was a little bit long path. I'll try making it short and other things. Thanks

**Comment by marcussacana** [comment]
If you find the reason let me known.

**Comment by JNKD0G** [comment]
Okay my friend. I found out It doesn't read the fpkg when it is in a file or more. It works only if you drag and drop, or if the fpkg is not inside any file. + Now the file doesn't want to install on the ps4. On the ps4 I get a notification says the payload received but nothing happens.

**Comment by marcussacana** [comment]
I didn't understand it, what you mean with pkg isn't inside of any file or when is in a 'file or more'?
About the notification, first thing you may try is ensure the PC IP field is right, then restart the DPI, also, restart the PS4 too since we don't know if the DPI failed service still running. (unless you saw a error/exit message)

**Comment by JNKD0G** [comment]
I meant the path was long and it seems like it was the problem. I've tried restarting DPI and the PS4 but the file doesn't send. I still get DPI error on the ps4. thanks

**Comment by marcussacana** [comment]
What is the DPI error code that you have?

**Comment by JNKD0G** [comment]
![IMG_20230213_155034](https://user-images.githubusercontent.com/120760361/218490858-a8a7f936-faee-4b1b-8a28-073d91812c08.jpg)

I don't know, it just says DPI : GET INFO ERROR

**Comment by marcussacana** [comment]
Get Info Error is usually blocked ports, you may look need allow the DPI in the firewall.
If you firewall isn't the problem, ensure if the PC IP is correct in the DPI.

**Comment by marcussacana** [comment]
if you still have error, you can open this issue again.
