### ISSUE TITLE
Doesn’t work on MacOS Ventura 13.3.1 

### ISSUE THREAD

**Issue by Yoyopizzacat** [marcussacana/DirectPackageInstaller#36]
I can’t get it to run even after using chmod +x and running it from terminal. Nothing happens and I have no clue what to do. I have an Android phone is that a better option?

**Comment by marcussacana** [comment]
The console shows any output error or any crash.log file is created?

**Comment by Yoyopizzacat** [comment]
/Users/.../Downloads/OSX-ARM64/DirectPackageInstaller.Desktop
zsh: killed     /Users/.../Downloads/OSX-ARM64/DirectPackageInstaller.Desktop

**Comment by marcussacana** [comment]
Did you have a ARM64 mac or x64?, and just to be sure, you downloaded what build of the DPI?

**Comment by marcussacana** [comment]
it's not the same usually, unless you have a high end phone.

So this happens in the ARM64 build?... it's a bit hard to me find what is wrong since I don't have a M1 Mac.
You installed the .NET 6, right?

**Comment by Yoyopizzacat** [comment]
yeah but don’t worry too much I’ll just use my phone or hdd or ssd. thanks!

**Comment by Yoyopizzacat** [comment]
Hi marcussacana, I tried the x64 version and it worked! Thank you so much!

**Comment by marcussacana** [comment]
wtf, and your computer is a M1?

**Comment by Yoyopizzacat** [comment]
Yeah. Also I ran into a slight issue which seems to be the same as this guy
https://www.reddit.com/r/PS4Hacks2/comments/zc7dn8/i_am_trying_to_send_fake_pkg_over_direct_package/?utm_source=share&utm_medium=web2x&context=3

**Comment by marcussacana** [comment]
Get info error means that the PS4 failed to connect to your PC, this might be the PC with incorrect IP or firewall blocking the connection.
