### ISSUE TITLE
"Seeking Assistance with 'Remote Package Installer' and 'GoldHEN' Error

### ISSUE THREAD

**Issue by Tarkhagal** [marcussacana/DirectPackageInstaller#39]
Hello, I've been experiencing an issue intermittently where I receive an error message that says 'Remote Package Installer' or 'GoldHEN' is not found at the IP address 192.168.x.x. It asks me to verify if it's running. Despite this issue, my PlayStation is up and running, and I can use other software like FileZilla without any problems. Could someone please assist me with this ?

<img width="628" alt="Screenshot 2023-09-26 212242" src="https://github.com/marcussacana/DirectPackageInstaller/assets/145452931/7b226ec4-dda2-4d77-bfbb-ee5d79f04dc6">

**Comment by marcussacana** [comment]
Are you using goldhen or remote package installer?

**Comment by Tarkhagal** [comment]
It depends mostly goldhen

**Comment by marcussacana** [comment]
Did you tried disable-enable the goldhen payload server when that happens or restart the direct package installer?
