### ISSUE TITLE
Duvida

### ISSUE THREAD

**Issue by xchneider** [marcussacana/DirectPackageInstaller#41]
Amigo, será que tem a opção de fazer isso via web? apenas para colocar na hospedagem, e fazer online? assim eu abro a porta do binloader para meu ps4, e entro no site, que coloquei o DirectPackageInstaller, coloco a URL, o ip externo do meu ps4, pronto! 
Ou, conseguir adicionar o Link no site, e acessar o site pelo ps4, e apenas clicar? estilo a loja do PKG-ZONE, ou Gamebato, que consigo baixar direto do navegador do ps4?

**Comment by marcussacana** [comment]
Não com a implementação inicial, será necessário fazer uma implementação de servidor http no binloader
