### ISSUE TITLE
i tried to download zip files but...

### ISSUE THREAD

**Issue by tehrzky** [marcussacana/DirectPackageInstaller#42]
but it's not working. it needs to be pkg. (pkg is working)

can you add download any files? just like a normal download manager not exclusive for pkg. 
can i download files from archive.org?  

im planning to just throw link on your app that will directly download roms/iso on ps4. ty

**Comment by marcussacana** [comment]
Unfortally, the PS4 does not accept download anything other than saves and pkgs, transfer other type of file to PS4 should be done with proper tools like FTP and webDAV.
