### ISSUE TITLE
mac os issue

### ISSUE THREAD

**Issue by edmark21** [marcussacana/DirectPackageInstaller#43]
![Uploading image.png…]()
how can I change the paths of where the DirectPackageInstaller store his data? cause for every time i submit and load it i will got an notification in ps4 abt the payload and after a few minutes it says dpi error but in the mac it wont says sent on mac

curently im runing m1 chip

**Comment by marcussacana** [comment]
Your image is not working.
Currently there are no way to change the DPI data path, but your problem is that  you are probabbly using the app build for macOS, you should use the non app version (start with terminal) and should be able to write the temporary files.
