### ISSUE TITLE
Can I use network sharing to increase the transfer speeds of already downloaded PKGs?

### ISSUE THREAD

**Issue by Chromeyyy** [marcussacana/DirectPackageInstaller#44]
With Remote Package Installer, I can connect my Laptop and PS4 together with an Ethernet cable and this increase the transfer speed A LOT, and this is done by enabling network sharing in my laptop settings. Can I do that with Direct Package Installer?

**Comment by marcussacana** [comment]
I used a lot DPI with direct ethernet cable, works fine, just be sure to setup correctly the connection.

**Comment by marcussacana** [comment]
Just be aware that is if you send the package with the DPI, you can' do, for example, put the file in a shared network connection and expect to the PS4 be able to find your files by the ethernet cable.

**Comment by Chromeyyy** [comment]
Yes, I understand. This will work with DPI, right? I just wanted to confirm. Also thank you for this amazing tool.

**Comment by marcussacana** [comment]
Yeah, it works.

**Comment by Chromeyyy** [comment]
Ok. Thank you so much mate
