### ISSUE TITLE
Failed to restart the server

### ISSUE THREAD

**Issue by daltonguitar** [marcussacana/DirectPackageInstaller#45]
spec info
running macOS 10.15.7
running latest version of DirectPackageInstaller for macOS with
PS4 on v9.00 GoldHen v2.3

When attempting to install pkg from my mac with the remote package application on in the ps4, I receive an "Unable to set up prerequisites for package".  When attempting to install pkg from my mac with the remote package application running in the background the ps4, I receive an error on the Ps4 "DPI Get Info Error"

I attempted to restart the server on another Port. When attempting to restart server I receive this error.

Failed to restart the server, Report a Bug:
System.InvalidOperationException: Webserver is already stopped.
at HttpServerLite.Webserver.Stop() in C:\Users
\Marcus\Documents\GitHub\DirectPackageInstaller\HttpServerLite\src\HttpServerLite\Webserver.cs:line 297
at DirectPackageInstaller.Host.PS4Server.Stop() in C:\Users
\Marcus\Documents\GitHub\DirectPackageInstaller\DirectPackageInstaller\DirectPackageInstaller\Host\PS4Server.cs:line 87
at DirectPackageInstaller.Views.MainView.RestartServer_OnClick(Object sender, RoutedEventArgs e) in C:\Users
\Marcus\Documents\GitHub\DirectPackageInstaller\DirectPackageInstaller\DirectPackageInstaller\Views\MainView.axaml.cs:line 1027

**Comment by marcussacana** [comment]
Are you using any firewall that might be blocking the DPI?

**Comment by marcussacana** [comment]
For now, close the DPI, try change in the Settings.ini the `ShowError` to True, try again until you get the "DPI Get Info Error"
This time an file with the name `DPIServer.log` should appear in the program directory, upload it here for me.

**Comment by daltonguitar** [comment]
I made sure to disable firewall-issue persists

Here is the DPIServer.log you requested after I received the "DPI Get Info Error". 
[DPIServer.log](https://github.com/marcussacana/DirectPackageInstaller/files/15044639/DPIServer.log)

The server log seemed to be showing very little before I got the error so Ill attach the error.log and crash.log as well

[DPI-ERROR.log](https://github.com/marcussacana/DirectPackageInstaller/files/15044690/DPI-ERROR.log)
[DPI-CARSH.log](https://github.com/marcussacana/DirectPackageInstaller/files/15044692/DPI-CARSH.log)

**Comment by marcussacana** [comment]
`System.Net.WebException: The remote server returned an error: (500) Internal server error.`
It seems that the Remote Package Installer returned 500 error, we need to know why now.

You said that RemotePackageInstaller was running in background, but it shouldn't works in background as far I know.

Did you tried the playload method as well (With RPI closed)?

**Comment by daltonguitar** [comment]
Weird
When I attempt to push to the ps4 with RPI closed or in the background I get the "DPI Get Info Error" appear on the ps4. When I have RPI opened on the ps4 and attempt to push I get "Unable to set up prerequisites for package 'http:W(ip address)VfileV?
b64=L1VzZXJ...

I am going to restart ps4 and if its not working I will reinstall RPI

**Comment by marcussacana** [comment]
Your PC IP is correct? 
If the DPIServer.log still empty this means that the DPI was able to connect to your PS4, but your PS4 wasn't able to connect to your PC back.
So, this might be a bad network confirguration somewhere.

**Comment by daltonguitar** [comment]
Let me look an verify, it was auto added so I never even checked
I appreciate all the help btw thank you!

**Comment by daltonguitar** [comment]
Looks like that was the issue, PC IP was wrong. changed it and restarted both devices and package is now being sent. It looks like the pkg is stuck downloading at around 75%, is that to be expected during a pkg download?

**Comment by daltonguitar** [comment]
download went through, looks like restart server is working now too. Thanks for the help marcus!

**Comment by marcussacana** [comment]
The download stuck may happen only if you are downloading from a compressed file directly or an bad file hosting service like 1fichier that does not allow download resume.

If you are installing the pkg locally, then shouldn't stuck at all.

**Comment by marcussacana** [comment]
Any problem should be looged in the files, if you need more help just report it with the logs.
