### ISSUE TITLE
Does this supports splitted PKG?

### ISSUE THREAD

**Issue by polybiusproxy** [marcussacana/DirectPackageInstaller#5]
Hello, I've been trying to download a PKG splitted in 11 parts.
7 parts are on a folder, and the rest 3 parts are on another.

I don't know how to make it download.

**Comment by polybiusproxy** [comment]
![image](https://user-images.githubusercontent.com/47796739/146679179-52d23519-1698-4323-80db-ba8bca931831.png)
Nevermind! I used Mediafire instead of Google Drive and it worked!

**Comment by polybiusproxy** [comment]
I gotta this app is awesome, now I don't need to install the PKGs on my computer!

**Comment by marcussacana** [comment]
how you gave the links to the program? you tried put the folder link or the part link list?

**Comment by polybiusproxy** [comment]
> how you gave the links to the program? you tried put the folder link or the part link list?

Folder links don't work, so I used the part link list

**Comment by marcussacana** [comment]
Yeah, but I wanted know if it's a bug or if you failed using the link because you tried use a folder link.
Then, the drive link failed and you used the link list, right?
In that case can you send me the link that you tried to my email? ddtank.marcus@gmail.com

**Comment by polybiusproxy** [comment]
The Mediafire way didn't work.
Download on the PS4 randomly stopped.

**Comment by polybiusproxy** [comment]
It may be because the game is 40 GB.

**Comment by marcussacana** [comment]
Then the decompressor still unstable to keep the connection...
Maybe can be the seek blocker, I can try disabled it later.
Mediafire links are stable, strange, what is your connection speed?

**Comment by polybiusproxy** [comment]
> Then the decompressor still unstable to keep the connection... Maybe can be the seek blocker, I can try disabled it later. Mediafire links are stable, strange, what is your connection speed?

Aroximately around 280Mbps per second. (that's what i see on the ps4 download)

**Comment by marcussacana** [comment]
yup, should be a problem with the tool then.

**Comment by polybiusproxy** [comment]
> yup, should be a problem with the tool then.

it's maybe an issue with the timeout?
the game im trying to download is Marvel's Spiderman,

it's split in 21 rars

**Comment by polybiusproxy** [comment]
@marcussacana just sent you an email!

**Comment by marcussacana** [comment]
is a possibility, or the mediafire link of one of the parties expired and hindered the extraction, it is complicated, to test I will need to use premium link generators to see if it is something related to the link expiring quickly, it could also be timeout or there was a problem with the download and returned corrupt data to the extractor.

**Comment by polybiusproxy** [comment]
> is a possibility, or the mediafire link of one of the parties expired and hindered the extraction, it is complicated, to test I will need to use premium link generators to see if it is something related to the link expiring quickly, it could also be timeout or there was a problem with the download and returned corrupt data to the extractor.

ok!
idk if its useful, but im not using proxy downloads on the options

**Comment by marcussacana** [comment]
downloading from rar will ignore that setting, since it's required to the download

**Comment by polybiusproxy** [comment]
> downloading from rar will ignore that setting, since it's required to the download

i see

**Comment by marcussacana** [comment]
I'm currently testing the zippyshare rar decompression, but it's very slow the download speed, then I can only wait
![image](https://user-images.githubusercontent.com/10576957/146682504-411b4d76-d95d-4150-ba7c-95e815898913.png)

**Comment by marcussacana** [comment]
after that, if nothing wrong happen I will test your links

**Comment by polybiusproxy** [comment]
> after that, if nothing wrong happen I will test your links

alright!
i only know one site to get ps4 games, but that pages gives them in compressed pkgs and .rar files

**Comment by polybiusproxy** [comment]
Actually, I give up.
I downloaded the full game on my PC, and I'm now transfering it through FTP (60 MB/s).
