### ISSUE TITLE
rar passwords

### ISSUE THREAD

**Issue by SDCryo** [marcussacana/DirectPackageInstaller#52]
I have noticed that rar files with a password requirement are straight unloadable  and the DPI will just end up with that "decompressing" message forever, so it would be nice if you can add an option when adding a file that asks if it requires a password or not, if yes it just asks for a password (also i have never tried it with already downloaded rar files only urls, I mean If I had the files I would've just put the password myself and extracted it ) (never tried zip but it might be the same) (mobile app)
![Screenshot_2024-06-18-18-32-22-743_com marcussacana DirectPackageInstaller](https://github.com/marcussacana/DirectPackageInstaller/assets/173189977/f3dfcb6c-a77b-40a6-a3a3-24a566c119fe)
case)
Edit: I did a bit of testing and sometimes after a while it just gives you the "no PKG found" or something like that

**Comment by marcussacana** [comment]
There are a bug in the library that DPI uses to decompress files, I reported and it was fixed today, I can just wait the next version
https://github.com/adamhathcock/sharpcompress/issues/844#event-13200578620

**Comment by marcussacana** [comment]
Consider too that the download linke that you used might not support resume download, in that case the decompressing will be stuck until the entire rar file is downloaded, for compressed files I highly recommend use Alldebrid or Realdebrid.

**Comment by SDCryo** [comment]
> uses

Thanks for help
