### ISSUE TITLE
OSX ARM64

### ISSUE THREAD

**Issue by BruhhIsmaell** [marcussacana/DirectPackageInstaller#53]
How do I get the program running, I've tried everything and I still can't get the program to open.

**Comment by marcussacana** [comment]
As said in readme, install the .net 6, open the terminal in the DPI directory and run the command `dotnet DirectPackageInstaller.Desktop.dll`

**Comment by BruhhIsmaell** [comment]
> As said in readme, install the .net 6, open the terminal in the DPI directory and run the command `dotnet DirectPackageInstaller.Desktop.dll`



> As said in readme, install the .net 6, open the terminal in the DPI directory and run the command `dotnet DirectPackageInstaller.Desktop.dll`

ahhhh thank you! I had to install .net 6 and .net sdk 6 to run it.
