### ISSUE TITLE
Support to https://datanodes.to/

### ISSUE THREAD

**Issue by SuperUmesh** [marcussacana/DirectPackageInstaller#55]
Hi,

I’m having trouble with downloading files from datanodes.to using DirectPKGInstaller (DPI). Sometimes the downloads work, but other times they fail with errors.

Could you please look into improving support for datanodes.to? Fixing this issue would help make downloads more reliable and allow users to download files directly to their phones without extra apps.

Thanks for your help!

**Comment by marcussacana** [comment]
Support Added, now you can paste non direct freemium links of DataNodes 
![DirectPackageInstaller Desktop_qAy4wmGF7q](https://github.com/user-attachments/assets/997b7368-857f-426b-a8fa-f06e8409c3cc)

**Comment by SuperUmesh** [comment]
Hi @marcussacana,

Thank you for adding support for non-direct freemium links from datanodes.to. I really appreciate your quick response and effort.

Thanks again for your help!
