### ISSUE TITLE
datanode links not loading pkg 

### ISSUE THREAD

**Issue by smitty4xx** [marcussacana/DirectPackageInstaller#57]
So when i put in most datanode links to load pkg  it’s brings up this ![image](https://github.com/user-attachments/assets/2939ed0e-79d6-4964-a606-28dba2fad20f) but when i connect to my hotspot it loads it just fine and i can send the pkg problem is i only have 10gb on my hotspot so can’t use it i get its some kind of issue with my wifi but what? and anyway to fix it? much thanks

**Comment by marcussacana** [comment]
I need to know your android version, and if possible send the link that you are having trouble to my email ddtank.marcus@gmail.com

**Comment by smitty4xx** [comment]
Sent to ur email and well i’m using a modified kindle fire tablet i thought maybe that’s the issue but same thing happens on my chromebook

**Comment by marcussacana** [comment]
Something similar happened in PS4, it seems the datanode is using some new HTTPS certificate and outdated device does not recognize well, maybe I may setup DPI to ignore the SSL errors but not sure if that will works yet.

**Comment by smitty4xx** [comment]
Oh okay i see well that would be awesome if it were to work and also my kindle tablet is running Fire OS 7.3.2.9 and my chromebook is running Chrome OS 103.0.5060.132 (64 bit)

**Comment by marcussacana** [comment]
Is possible copy and paste that error of your picture?
That will help a lot to analyze the problem.

**Comment by smitty4xx** [comment]
System.Net.WebException: net_http_ssl_connection_failed
→ System.Net.Http.HttpRequestException: net_http_ssl_connection_failed
→ System.IO.IOException: net_frame_read_size
at System.Net.Security.SslStream.GetFrameSize (ReadOnlySpan`1)
at System.Net.Security.SslStream.<ReceiveBlobAsync>d__176`1
[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=
6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
at System.Net.Security.SslStream.<ForceAuthenticationAsync>d__175`1
[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=
6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
at
System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthentic
ationOptions, HttpRequestMessage, Boolean, Stream, CancellationToken)
Exception_EndOfInnerExceptionStack
at
System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthentic
ationOptions, HttpRequestMessage, Boolean, Stream, CancellationToken)
at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage,
Boolean, CancellationToken)
at System.Net.Http.HttpConnectionPool. CreateHttp
11ConnectionAsync(HttpRequestMessage, Boolean, CancellationToken)
at System.Net.Http.HttpConnectionPool.AddHttp
11ConnectionAsync(HttpRequestMessage)
at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1
[[System.Net.Http.HttpConnection, System.Net.Http, Version=6.0.0.0,
Culture=neutral, PublicKeyToken=b
03f5f7f11d50a3a]].WaitWithCancellation (CancellationToken)
at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1
[[System.Net.Http.HttpConnection, System.Net.Http, Version=6.0.0.0,
Culture=neutral, PublicKeyToken=b
03f5f7f11d50a3a]].WaitWithCancellationAsync(Boolean, CancellationToken)
at System.Net.Http.HttpConnectionPool.GetHttp
11ConnectionAsync(HttpRequestMessage, Boolean, CancellationToken)
at
System.Net.Http.HttpConnectionPool.SendWithVersion DetectionAndRetryAsync(
HttpRequestMessage, Boolean, Boolean, CancellationToken)
(HttpRequestMessage, Boolean, Boolean, CancellationToken)
at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage,
Boolean, CancellationToken)
at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage,
CancellationToken)
at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage,
CancellationToken)
at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage,
CancellationToken)
at System.Net.Http.HttpClient.Send(HttpRequestMessage,
HttpCompletionOption, CancellationToken)
at System.Net.HttpWebRequest.SendRequest(Boolean)
at System.Net.HttpWebRequest.GetResponse()
Exception_EndOfInnerExceptionStack
at System.Net.HttpWebRequest.GetResponse()
at DirectPackagelnstaller.IO.PartialHttpStream.HttpRead(Byte[] buffer, Int32&
offset, Int32& count, Int32 Tries)
at DirectPackageInstaller.IO.PartialHttpStream.HttpRead(Byte[] buffer, Int32&ܝoffset, Int32& count, Int32 Tries)
at DirectPackageInstaller.IO.PartialHttpStream.HttpRead(Byte[] buffer, Int32&
offset, Int32& count, Int32 Tries)
at DirectPackageInstaller.IO.PartialHttpStream.HttpRead(Byte[] buffer, Int32&
offset, Int32& count, Int32 Tries)
at DirectPackageInstaller.IO.PartialHttpStream.Read(Byte[] buffer, Int32 offset,
Int32 count)
at System.IO.Stream.<>c.<BeginReadInternal>b__40_0(Object)
at System.Threading.Tasks.Task`1[[System.Int32, System.Private.CoreLib,
Version=6.0.0.0, Culture=neutral, PublicKeyToken=
7cec85d7bea7798e]].InnerInvoke()
at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object)
at
System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread,
ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
at
System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop (Thread,ExecutionContext, ContextCallback, Object)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread)
--- End of stack trace from previous location ---
at DirectPackagelnstaller.Views.MainView.BtnLoadOnClick(Object sender,
RoutedEventArgs e)

**Comment by marcussacana** [comment]
Thanks, I just commited some changes that might help (or not) with this, once the github action build finish, I will send you the new apk for testing.

**Comment by smitty4xx** [comment]
thank you so much for ur time and effort man

**Comment by marcussacana** [comment]
Check if this build works https://tmpfiles.org/12315332/android-arm64.zip

**Comment by smitty4xx** [comment]
I should’ve mentioned it won’t let me download the arm64 build only the arm build installs guessing that’s a hardware limitation

**Comment by marcussacana** [comment]
What build you usually install?

**Comment by smitty4xx** [comment]
the arm build 
![F48F4D61-45F7-4C2B-941C-40A4C9954E99](https://github.com/user-attachments/assets/e1444524-f09c-4cd9-b4ac-e8e631872719)

**Comment by marcussacana** [comment]
check this build then: https://tmpfiles.org/12316227/android-arm.zip

**Comment by smitty4xx** [comment]
tried a few different links and unfortunately got the same error

**Comment by marcussacana** [comment]
This case it seems I will need to upgrade to the .NET 8, I can't do it right now but Soon I will reply here to test a new build.

**Comment by marcussacana** [comment]
Check if this build works: https://file.io/Ay0m7IzGUrbp

**Comment by smitty4xx** [comment]
Same error

**Comment by marcussacana** [comment]
This one: https://file.io/cJ1JhVo0k0RC

**Comment by smitty4xx** [comment]
No luck it’s all good tho man i don’t wanna waste ya time at the least i can still use mediafire and other urls

**Comment by marcussacana** [comment]
Fine, I suspect the problem here is the system is using an old android version, I tried include the CA Cert manually but no lucky.

**Comment by smitty4xx** [comment]
I figured something along those lines thanks tho g ur app is a great convenience nonetheless👍🏽
