### ISSUE TITLE
User-Agent

### ISSUE THREAD

**Issue by Anuskuss** [marcussacana/DirectPackageInstaller#59]
I'm trying to detect DPI and it would be helpful if all HTTP requests had some User-Agent associated with it, e.g. `DirectPackageInstaller/6.2.12`.

**Comment by marcussacana** [comment]
I will do something in the next update.
But the user agent can be set only for the DPI requests or PS4 Proxied Downloads,
I can't change the user agent of the PS4 connection made by the system download.

**Comment by Anuskuss** [comment]
> I can't change the user agent of the PS4 connection made by the system download.

I can already detect the PS4 via `*PlayStation 4*`. I just need a way to detect the 2+ connections DPI makes (`HEAD` and `GET`+`Range:bytes`).

**Comment by marcussacana** [comment]
Done, User Agent flag is DPI/Version
