### ISSUE TITLE
Can't make the Direct Package installer find my PS4

### ISSUE THREAD

**Issue by Ajax573** [marcussacana/DirectPackageInstaller#6]
Hi!
I tried the direct package installer because the actual concept of just directly installing pkg files directly to your computer sounded amazing.
I tried zippy links (which were divided) i copied them all entered them into the program. It seemed to pick up on all the links (they were compressed rar) but for some reason the program couldn't find the Remote Package installer on the PS4 even though it was open up and running. I reentered the IP plenty of times but i couldn't make it find it. Has anyone experienced this? Is there a solution to it?

**Comment by marcussacana** [comment]
Hmm, try restart your PS4 for now, I had this problem before and the RPI just didn't reply any call to their api for some reason.
`http://{PS4IP}:12800/api/install` is an url that you can open in your browser and check if the RPI is responding, you must see a error message about invalid call in the api or something like that.
if the RPI isn't responding the browser will load for a good time and will timeout

**Comment by marcussacana** [comment]
By the way, the RAR feature is reported to have bugs right now, I don't recommend use while don't be fixed.

**Comment by Ajax573** [comment]
I did what you said and you were right, the site timed out and then gave me an error. Thank you for the quick reply atleast now i know why it isn't working. Has this happened before?

**Comment by marcussacana** [comment]
This happen with me sometimes and only when I restart my PS4 is solved, Not sure yet, but I supose is caused by the Auto Detection of the PS4 IP of my tool, should be solved if you disable the SearchPS4 and set a valid IP manually
![image](https://user-images.githubusercontent.com/10576957/146697943-64d77d43-fe0f-411d-a1bc-a3bb8cc7154b.png)

**Comment by Ajax573** [comment]
Hello again my friend.
It seems your tool is not in the fault, i did what you said. I disabled the auto detection and the IP was correctly put in. It still gave me an error that it can't find the RPI on the IP. Might be an issue with the actual Remote Package Installer.

**Comment by marcussacana** [comment]
you're on firmware 9.0?

**Comment by Ajax573** [comment]
Yes, it's jailbroken and everything

**Comment by Ajax573** [comment]
Hello my friend, i searched around and had a person telling me i need to have the PCs ip adress also put into the direct package installer but there is no bar for me to do so. Is this true or false?

**Comment by marcussacana** [comment]
This tool works with an automatic ip detection, therefore don't have option to insert the IP manually
