### ISSUE TITLE
After a while, PS4 just says "Cannot install"

### ISSUE THREAD

**Issue by Duckbuster** [marcussacana/DirectPackageInstaller#60]
PS4 Pro 5.05 GoldHen v2.4b14 and v2.4b16.2 tried.
DPI: 6.2.13 x64
OS: Win11 23H2

Tried DPI without Segmented downloads and CNL support options.
(Proxy server is off)

When starting installing a package it starts and works for a bit, then it will just error after a while on the PS4. (CE32318-3)
No idea if I'm doing anything wrong.

**Comment by Duckbuster** [comment]
Seems like I fixed it by enable debug setings in GoldHen then go to settings,  scroll down to the bottom for *Debug Settings -> Playstation Network -> then set NP Environment to sp-int

**Comment by marcussacana** [comment]
pretty strange this one, but i'm glad that you found a fix.
