### ISSUE TITLE
Send to /data/pkg

### ISSUE THREAD

**Issue by LuisAragonLetona** [marcussacana/DirectPackageInstaller#61]
I get different errors when I send rar files, It won't work for me, I have to download the rar files, extract the pkg, send to /data/pkg using ftp and it works using the package installer from Goldhen. I'd like to have an option to send the extracted pkg to /data/pkg

**Comment by marcussacana** [comment]
Hi, if you are planning to upload the file to /data/ and install with goldhen there are no point in using DPI.
About the RAR, be sure to use services like alldebrid and disable the segmented download.
