### ISSUE TITLE
Direct Download Mode not working

### ISSUE THREAD

**Issue by mha53** [marcussacana/DirectPackageInstaller#64]
direct download mode 

package sent 

in ps4  downloads not download give me error

**Comment by marcussacana** [comment]
I need more details, are your PS4 able to connect the internet (Like are you using offline dns)?
Are you trying download from what url? (send to my email)
what error you see?

**Comment by mha53** [comment]
ps4 connected  to Wi-Fi  internet 
Download url : \*link removed\*
goldhen binloader  :enabled 
error : ce-37732-2

-----------------------
when using remote package installer 
 enable direct download mode  i should uncheck : proxy + segment   ,, right?

**Comment by marcussacana** [comment]
The url appears to use an domain that is not valid, are you sure the url is correct?

**Comment by mha53** [comment]
> The url appears to use an domain that is not valid, are you sure the url is correct?

the url is working 
i tried the proxy  mode  and segment 
both worked

**Comment by marcussacana** [comment]
Okay, Whois clear said the domain does not exists, did you tried install from other hosting service? if not please test it.

**Comment by mha53** [comment]
When I click load 
It does show the game and all details name version etc 
Click Install it give me package sent , also show in PS4 downloads starting downloads then give error

**Comment by marcussacana** [comment]
Try install with Proxy Mode enabled or switch to other hosting service, 
Not sure if this domain is something that you made in your local network or is something limited of your contry, but whois services pointed to that domain not exists.

**Comment by mha53** [comment]
The link from **
There's a new option to direct download PKG for ps4

**Comment by marcussacana** [comment]
I recommend ask support with the site, the domain st1.reanoz.gg isn't really valid, not sure why it works in your PC, if you typed the url manually might be some typo.

**Comment by mha53** [comment]
i checked my router security i was blocking  ps4 updates    i disabled them 
and now it's working on direct mode 
i checked the list  gs2.ww.prod.dl.playstation.net that was causing the problem not to start download 
weird, i've deleted all the list and switch   nomadic  dns  and it's working
