### ISSUE TITLE
DirectPackageInstaller - Error Reading PKG files

### ISSUE THREAD

**Issue by Sn00pyB3asT** [marcussacana/DirectPackageInstaller#65]
My DPI worked for the first time when i pasted the link, but i had problems with Remote Package Installer. After I reinstalled RPI I tried again with DPI but it keeps throwing error ( Failed to open PKGs ). I have tried at least 2 sites 1fichier and gofile.

![DPI-error](https://github.com/user-attachments/assets/bb51d90b-04a0-424a-8f9b-cf1ac7c0fc16)
![DPI-error2](https://github.com/user-attachments/assets/c45e478b-776d-49ef-91ae-f43415a5e201)

Here are the screen shots of DPI and an error.log file.

**Comment by marcussacana** [comment]
Go file isn't supported
