### ISSUE TITLE
DPI: Get info error

### ISSUE THREAD

**Issue by KihonBlue** [marcussacana/DirectPackageInstaller#67]
I am trying to send packages from my computer (NOT the internet) which is connected to the same router as the PlayStation 4. The PS4 displays the message "packaged received from "my IP address" but nothing gets sent, then after about 2-3 mins the message appears "DPI: Get info error".

Before updating to version 8.0 of DPI everything worked fine! Boo Hoo! You smart computer programmer people really should take it into consideration that there are a lot of lay people out there that have no idea what you're talking about and just want to use your software to do the job without having to understand all the complicated stuff. Cheers!

PS thanks for your program that worked for years for me.

**Comment by marcussacana** [comment]
Well the 8.0.0 itself changes it just the new DHCP feature that is disabled by default, shouldn't cause any problem at all.
The most suspect should be the upgrade from .NET 6 to .NET 8 instead.
First, if you are lazy or does not wanna spent time looking into the problem the .NET 6 version still possible to use by just downloading from the [release history](https://github.com/marcussacana/DirectPackageInstaller/releases/tag/6.2.13), if you are here to find a soluction instead we will need begin trying to find out what would be wrong.

By what you said the PS4 pop up the "Payload Received" message, this means the Direct Package Installer has able to connect to your PS4, as well means that the goldhen binloader server is running, everything fine until now.

The "DPI: Get Info Error" means that the PS4 hasn't able to collect from your PC the PKG details.
And this may happen due a couple of reasons but the 2 most common should be:
1 - Firewall or antivirus is now blocking the DPI after the .NET 8 update (Frankly, I think is the most probably)
2 - Your PC LAN IP changed and the DPI still trying use the old IP, therefore the PS4 can't find your computer to connect it.

Please, ensure those two cases aren't your one (I really recommend temporally disable the entire firewall to test it)

**Comment by KihonBlue** [comment]
Hello, thank you for your quick reply.
I turned off Windows Defender firewall and now the package has been received and working.
While I am here what are the options, proxy downloads, segmented downloads, CNL support and DHCP server for, should I have them ticked?
Thanks again.
Happy New Year.

**Comment by marcussacana** [comment]
The recomendation from be will be:
1 - Proxy Download enabled only if you download PKGs from direct links
2 - Segmented Download Disabled
3 - CNL Support enabled if you does not use JDownloader, this feature can be used to integration with the "filecrypt" service.
4 - DHCP Server can be used if you connect your PC directly to the PS4 with an ethernet cable, if that's not the case just keep disabled.

**Comment by KihonBlue** [comment]
Thanks again for your reply, one last query, honestly! (I'm not good with network stuff!). With DHCP Server if I have PC connected to my router with ethernet cable and PS4 connected to same router with another ethernet cable (via a switch) does that count as PC connected directly to PS4 or do I need the cable going from PC Motherboard RJ45 direct to PS4 RJ45? Always wondered about that. Cheers!

**Comment by marcussacana** [comment]
Nop, this case DHCP Server is useless for you.
DHCP Server is basically a feature that automatically setup your network connection once you connect your PS4 directly into your PC with a cable, without any router.

**Comment by marcussacana** [comment]
I saw your message in kofi, seems everything is solved then I'm closing this issue.
Have a good new year.
