### ISSUE TITLE
unable to set up prerequisites for package

### ISSUE THREAD

**Issue by jaum20** [marcussacana/DirectPackageInstaller#8]
I'm getting this error when trying to install a splitted package [using a json from my entitlement.db](https://www.reddit.com/r/ps4homebrew/comments/rvo1ix/i_found_a_new_way_to_get_entitlement_pkgs_more/). It works for single package games (not splitted)
![Sem título](https://user-images.githubusercontent.com/36702273/148685779-8069e88f-2beb-4366-ae6a-0d77dcac5d0e.png)
.

**Comment by marcussacana** [comment]
I can't check what is wrong without the content url, if you want you can send to my email or debug the program.

**Comment by jaum20** [comment]
@marcussacana what's your email?

**Comment by marcussacana** [comment]
ddtank.marcus@gmail.com

**Comment by jaum20** [comment]
Sent

**Comment by Gkiokan** [comment]
This error happens when something is wrong with RPI on PS4.

Just restart your RPI and try again. It could be caused by an existing installed package, too.

**Comment by marcussacana** [comment]
Yeah, it's something that you did wrong.
If you restarted the RPI and don't solved, try restart the PS4.
![image](https://user-images.githubusercontent.com/10576957/148696628-2feb533a-a980-444e-a219-044141fccb53.png)
Because worked here

**Comment by marcussacana** [comment]
> Shouldn't the URL be a valid URL without \ ?

Yes, but the error message is the a json response created by the RPI.
Then it's just the json escaped url, nothing really wrong.

**Comment by Gkiokan** [comment]
In case if you haven't handled the other errors I've figured out the most common error values.
You can have a look into the json5 parsed error value [here](https://github.com/Gkiokan/ps4-remote-pkg-sender/blob/master/src/renderer/plugins/ps4.js#L140)
  
Excerpt:  
```
  // Found Error Codes
  // 2157510677 error on double install?
  // 2157510663 already installed?
  // 2157510681 task doesn't exist
  // 2157510789 (not known)

```

**Comment by marcussacana** [comment]
Yeah, that said I noticied that error as well don't reported any code...
Usually I saw that error when the RPI falied to read the PKG content, (since he before start the download read the pkg to extract the param.sfo and icon0.png)

**Comment by jaum20** [comment]
> This error happens when something is wrong with RPI on PS4.
> 
> Just restart your RPI and try again. It could be caused by an existing installed package, too.
> 
> Shouldn't the URL be a valid URL without \ ?
@marcussacana @Gkiokan 
Not luck. The same error persists

**Comment by marcussacana** [comment]
You didn't tried install this game before and failed? if that's the case try see the download history in the PS4 and delete the game.

**Comment by marcussacana** [comment]
By the way, you're using the last DirectPackageInstaller version, right? a certain version have a bug with the json that is already fixed.

**Comment by jaum20** [comment]
I just tried with https://github.com/BenjaminFaal/ps4-remote-pkg-installer and it worked. Not sure why it didn't work with your tool

**Comment by marcussacana** [comment]
Strange, since worked with me.
but isn't strage work in this tool because my one deal to merge the split pkg and send as a single file to PS4, the remote pkg installer I think just send the json url to the ps4, by the way, the version mainted by the @Gkiokan is better.

**Comment by Gkiokan** [comment]
I think it happens when you serve a file somewhere else on another server where it has many other circumstates and I assume it has something with the type of serving to do but I am not sure yet. Just digging arround and found out if you serve in chunks you get another error on RPI. System files object blabla. 

@marcussacana let's discuss this on a deep tech level. Could you message me at discord? Gkiokan#0735

**Comment by marcussacana** [comment]
your discord tag looks is wrong or you have high privacy settings

**Comment by Gkiokan** [comment]
Oh yea. Had a mac os bug yesterday while adding new features. I killed the event Listener for all of mac commands lol. 
Here you go Gkiokan#0735

**Comment by marcussacana** [comment]
We came to the conclusion that this error is usually related to connection failure, for some reason the RemotePackageInstaller could not load the SFO, Icon or read the PKG header, so we have this error. (IO Error can cause that as well)

There are a lot of possibilities to a http connection failure, then I can't really reproduce your problem to debug what is happening.

**Comment by jaum20** [comment]
@marcussacana 
Can I provide logs or something?

**Comment by marcussacana** [comment]
there is no log.
Only debugging is possible to identify the problem.

**Comment by marcussacana** [comment]
If you want you can install the visual studio 2019 and run the project from the source to be able debug.

**Comment by marcussacana** [comment]
I did this version with log to you give a try, but I don't think this will help much.
[DPI Debug.rar.zip](https://github.com/marcussacana/DirectPackageInstaller/files/7919914/DPI.Debug.rar.zip)

**Comment by jaum20** [comment]
I don't see an option to enab the logs. Anyway, this version worked with not errors

**Comment by marcussacana** [comment]
What the fuck....
well, there is no option, he just generate the log in the program folder...

**Comment by yigal33** [comment]
hi i try 1ficiher not wok faild to open pkg 
any guide how to work with 1ficher?
thanks

**Comment by marcussacana** [comment]
what url you tried?

**Comment by yigal33** [comment]
I tried both the first link and the second This is the first
https://1fichier.com/?d4ggyocxhbb0aa5j6emr&af=2850246

בתאריך יום א׳, 30 בינו׳ 2022, 22:30, מאת Marcus André ‏<
***@***.***>:

**Comment by marcussacana** [comment]
I see, the problem is because the PKG is in a RAR, for now the 1fichier is supported only by decompressed PKGs, but Soon I will add support for compressed files as well.

**Comment by yigal33** [comment]
Ha ok because a lot of files in 1fichier compresses it would be great if
you fix it thanks a lot for the investment and hard work.

בתאריך יום א׳, 30 בינו׳ 2022, 22:48, מאת Marcus André ‏<
***@***.***>:

**Comment by yigal33** [comment]
hi also pkg that no rar on 1ficher not work.

try this

https://1fichier.com/?jtu3kmbpzzb4xevcydrq&af=2850246

‫בתאריך יום א׳, 30 בינו׳ 2022 ב-22:48 מאת ‪Marcus André‬‏ <‪
***@***.***‬‏>:‬

**Comment by marcussacana** [comment]
@yigal33 what error you saw?

**Comment by yigal33** [comment]
falid to open pkg.

בתאריך יום ב׳, 31 בינו׳ 2022, 21:41, מאת Marcus André ‏<
***@***.***>:

**Comment by marcussacana** [comment]
@yigal33 it's working here
![image](https://user-images.githubusercontent.com/10576957/151876700-7dc0fa53-7f52-4a63-b2a3-5706f1f0dd04.png)

**Comment by yigal33** [comment]
Did you do anything special? Can you elaborate on what exactly you did?
I do not succeed when I insert the link and click Load software gets stuck.

thanks.


בתאריך יום ב׳, 31 בינו׳ 2022, 23:34, מאת Marcus André ‏<
***@***.***>:

**Comment by marcussacana** [comment]
Copied the link that you sent and put in the text box, then press Load, it freeze but just for a while, this will be optimized in the next update by the way.

**Comment by yigal33** [comment]
i must to open rpi on ps4 to make this load on a pc? or not doesnt need?

בתאריך יום ג׳, 1 בפבר׳ 2022, 10:41, מאת Marcus André ‏<
***@***.***>:

**Comment by marcussacana** [comment]
To load you don't need, but to install you need it.

**Comment by yigal33** [comment]
test it again not work

not respoting number of time and  after a while  nessge bad host or somting
like that.

anway you have discord?

בתאריך יום ג׳, 1 בפבר׳ 2022, 11:21, מאת Marcus André ‏<
***@***.***>:

**Comment by marcussacana** [comment]
Marcus André#0956

**Comment by yigal33** [comment]
after 2 min it load

בתאריך יום ג׳, 1 בפבר׳ 2022, 19:52, מאת Marcus André ‏<
***@***.***>:
